<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>generate-steps</AssemblyName>
    <RootNamespace>ApiTestFramework.OpenApi.Cli</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ApiTestFramework.OpenApi\ApiTestFramework.OpenApi.csproj" />
  </ItemGroup>

</Project>
