// Auto-generated by tools/generate_k6.py — DO NOT EDIT, regenerate instead.
// Source: OpenAPI specs in tests/ApiTestFramework.Clients/swagger/
import http from 'k6/http';
import { check, group, sleep } from 'k6';
import { Rate } from 'k6/metrics';

const AUTH_BASE_URL = __ENV.AUTH_BASE_URL || "http://localhost:5300";

const PROFILES = {
  smoke:  { vus: 2, duration: '30s' },
  load:   { stages: [ { duration: '30s', target: 20 }, { duration: '2m', target: 20 }, { duration: '30s', target: 0 } ] },
  stress: { stages: [ { duration: '1m', target: 25 }, { duration: '2m', target: 50 }, { duration: '2m', target: 100 }, { duration: '1m', target: 0 } ] },
};
const profile = PROFILES[__ENV.PROFILE || 'smoke'];

export const options = {
  ...profile,
  thresholds: {
    http_req_duration: ['p(95)<500'],
    checks: ['rate>0.99'],
    errors: ['rate<0.01'],
  },
};

const errorRate = new Rate('errors');

export default function () {
  const uniq = `${__VU}_${__ITER}_${Date.now()}`;
  const headers = { 'Content-Type': 'application/json' };
  const username = `perf_user_${uniq}`;
  const password = 'P@ssw0rd_123!';

  group('register + login', () => {
    const regRes = http.post(`${AUTH_BASE_URL}/api/auth/register`,
      JSON.stringify({ username, email: `${username}@example.com`, password, role: 'User' }),
      { headers });
    check(regRes, { "POST register \u2192 201": (r) => r.status === 201 }) || errorRate.add(1);

    const loginRes = http.post(`${AUTH_BASE_URL}/api/auth/login`,
      JSON.stringify({ username, password }),
      { headers });
    const loginOk = check(loginRes, {
      "POST login \u2192 200": (r) => r.status === 200,
      'login returns token': (r) => Boolean(r.json().token.accessToken),
    });
    if (!loginOk) errorRate.add(1);

    sleep(0.1);
  });
}
