// Auto-generated by tools/generate_k6.py — DO NOT EDIT, regenerate instead.
// Source: OpenAPI specs in tests/ApiTestFramework.Clients/swagger/
import http from 'k6/http';
import { check, group, sleep } from 'k6';
import { Rate } from 'k6/metrics';

const AUTH_BASE_URL = __ENV.AUTH_BASE_URL || "http://localhost:5300";
const PRODUCT_BASE_URL = __ENV.PRODUCT_BASE_URL || "http://localhost:5100";

const PROFILES = {
  smoke:  { vus: 2, duration: '30s' },
  load:   { stages: [ { duration: '30s', target: 20 }, { duration: '2m', target: 20 }, { duration: '30s', target: 0 } ] },
  stress: { stages: [ { duration: '1m', target: 25 }, { duration: '2m', target: 50 }, { duration: '2m', target: 100 }, { duration: '1m', target: 0 } ] },
};
const profile = PROFILES[__ENV.PROFILE || 'smoke'];

export const options = {
  ...profile,
  thresholds: {
    http_req_duration: ['p(95)<500'],
    checks: ['rate>0.99'],
    errors: ['rate<0.01'],
  },
};

const errorRate = new Rate('errors');

function obtainToken() {
  const uniq = `${Date.now()}_${Math.floor(Math.random() * 1e6)}`;
  const registerPayload = JSON.stringify({
    username: `perf_user_${uniq}`,
    email: `perf_user_${uniq}@example.com`,
    password: 'P@ssw0rd_123!',
    role: 'User',
  });
  const res = http.post(`${AUTH_BASE_URL}/api/auth/register`, registerPayload, {
    headers: { 'Content-Type': 'application/json' },
  });
  if (res.status !== 201 && res.status !== 200) {
    throw new Error(`auth setup failed: HTTP ${res.status} ${res.body}`);
  }
  return res.json().token.accessToken;
}

export function setup() {
  const token = obtainToken();
  const data = { token };

  return data;
}

export default function (data) {
  const params = {
    headers: {
      'Content-Type': 'application/json',
      Authorization: `Bearer ${data.token}`,
    },
  };

  group("products CRUD", () => {
    const createPayload = 
    {
      "name": "Sample Name",
      "description": "Generated by tools/openapi_common.py",
      "price": 19.99,
      "stockQuantity": 50,
      "category": "Electronics"
    };
    let res = http.post(`${PRODUCT_BASE_URL}/api/products`, JSON.stringify(createPayload), params);
    check(res, { "POST /api/products \u2192 201": (r) => r.status === 201 }) || errorRate.add(1);
    const productId = res.json('id');
    res = http.get(`${PRODUCT_BASE_URL}/api/products`, params);
    check(res, { "GET /api/products \u2192 200": (r) => r.status === 200 }) || errorRate.add(1);
    res = http.get(`${PRODUCT_BASE_URL}/api/products/${productId}`, params);
    check(res, { "GET /api/products/{id} \u2192 200": (r) => r.status === 200 }) || errorRate.add(1);
    res = http.get(`${PRODUCT_BASE_URL}/api/products/category/${createPayload.category}`, params);
    check(res, { "GET /api/products/category/{category} \u2192 200": (r) => r.status === 200 }) || errorRate.add(1);
    res = http.put(`${PRODUCT_BASE_URL}/api/products/${productId}`, JSON.stringify({"name": "Sample Name", "description": "Generated by tools/openapi_common.py", "price": 19.99, "stockQuantity": 50, "category": "Electronics", "isActive": true}), params);
    check(res, { "PUT /api/products/{id} \u2192 200": (r) => r.status === 200 }) || errorRate.add(1);
    res = http.del(`${PRODUCT_BASE_URL}/api/products/${productId}`, null, params);
    check(res, { "DELETE /api/products/{id} \u2192 204": (r) => r.status === 204 }) || errorRate.add(1);
    sleep(0.1);
  });
}
