using ApiTestFramework.OpenApi.Models;
using System.Text;

namespace ApiTestFramework.OpenApi.Generator;

/// <summary>
/// Generates fluent test-data builder classes (C#) from OpenAPI request schemas.
/// <para>
/// Each object schema becomes a <c>partial</c> builder class with:
/// Bogus-based defaults (name/type heuristics), <c>WithX(value)</c> setters,
/// nested-builder overloads <c>WithX(Action&lt;XBuilder&gt;)</c> for object
/// properties, and <c>AddX / ClearX</c> methods for collections.
/// Hand-written customizations live in separate partial files and hook in via
/// <c>OnDefaultsApplied()</c> / <c>OnBeforeBuild(instance)</c> — they survive
/// regeneration.
/// </para>
/// </summary>
public static class BuilderScaffolder
{
    /// <summary>
    /// Generates one builder file per object schema.
    /// Returns a map of file name (e.g. <c>CreateOrderRequestBuilder.g.cs</c>) to file content.
    /// </summary>
    /// <param name="schemas">Request schemas (see SchemaExtractor.GetRequestSchemas).</param>
    /// <param name="dtoNamespace">Namespace of the DTO classes, e.g. ApiTestFramework.Clients.OrderService.</param>
    /// <param name="builderNamespace">Namespace for the generated builders.</param>
    /// <param name="sourceName">Name of the swagger source, used in the file header.</param>
    public static IReadOnlyDictionary<string, string> GenerateBuilders(
        IReadOnlyList<SchemaDefinition> schemas,
        string dtoNamespace,
        string builderNamespace,
        string sourceName)
    {
        var result = new Dictionary<string, string>();

        foreach (var schema in schemas.Where(s => !s.IsEnum))
        {
            result[$"{schema.Name}Builder.g.cs"] =
                GenerateBuilder(schema, dtoNamespace, builderNamespace, sourceName);
        }

        return result;
    }

    private static string GenerateBuilder(
        SchemaDefinition schema,
        string dtoNamespace,
        string builderNamespace,
        string sourceName)
    {
        var type = schema.Name;
        var builder = $"{type}Builder";
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated>");
        sb.AppendLine("//     Generated by ApiTestFramework.Generator.Cli — do not edit by hand.");
        sb.AppendLine($"//     Source: {sourceName} (schema: {type})");
        sb.AppendLine("//     Regenerate: scripts/regenerate-all.ps1");
        sb.AppendLine("//       (or: dotnet run --project tests/ApiTestFramework.Generator.Cli)");
        sb.AppendLine($"//     Custom logic belongs in a partial file: Builders/Custom/{builder}.cs");
        sb.AppendLine("// </auto-generated>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using Bogus;");
        sb.AppendLine($"using {dtoNamespace};");
        sb.AppendLine();
        sb.AppendLine($"namespace {builderNamespace};");
        sb.AppendLine();
        sb.AppendLine($"/// <summary>Fluent test-data builder for <see cref=\"{type}\"/>.</summary>");
        sb.AppendLine($"public partial class {builder}");
        sb.AppendLine("{");
        sb.AppendLine("    private static readonly Faker Faker = new();");
        sb.AppendLine($"    private readonly {type} _instance = new();");
        sb.AppendLine();
        sb.AppendLine($"    public {builder}()");
        sb.AppendLine("    {");
        sb.AppendLine("        ApplyDefaults();");
        sb.AppendLine("        OnDefaultsApplied();");
        sb.AppendLine("    }");
        sb.AppendLine();

        AppendApplyDefaults(sb, schema);

        sb.AppendLine("    // Partial hooks — implement in a non-generated partial file to customize;");
        sb.AppendLine("    // customizations survive regeneration.");
        sb.AppendLine("    partial void OnDefaultsApplied();");
        sb.AppendLine($"    partial void OnBeforeBuild({type} instance);");
        sb.AppendLine();
        sb.AppendLine($"    public {type} Build()");
        sb.AppendLine("    {");
        sb.AppendLine("        OnBeforeBuild(_instance);");
        sb.AppendLine("        return _instance;");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Escape hatch for edge cases the fluent API does not cover (e.g. explicit nulls).</summary>");
        sb.AppendLine($"    public {builder} With(Action<{type}> mutate)");
        sb.AppendLine("    {");
        sb.AppendLine("        mutate(_instance);");
        sb.AppendLine("        return this;");
        sb.AppendLine("    }");

        foreach (var prop in schema.Properties)
        {
            sb.AppendLine();
            AppendPropertyMethods(sb, builder, prop);
        }

        sb.AppendLine("}");
        return sb.ToString();
    }

    private static void AppendApplyDefaults(StringBuilder sb, SchemaDefinition schema)
    {
        sb.AppendLine("    private void ApplyDefaults()");
        sb.AppendLine("    {");

        var any = false;
        foreach (var prop in schema.Properties)
        {
            // Optional (nullable, not required) properties stay null by default.
            if (prop.Nullable && !prop.Required) continue;

            var defaultExpr = GetDefaultExpression(schema.Name, prop);
            if (defaultExpr is null)
            {
                var hint = prop.Kind == PropertyKind.Array
                    ? $"        // {prop.Name}: starts empty — add entries via Add{Singular(prop.Name)}(...)"
                    : $"        // {prop.Name}: no safe default — provide via With{prop.Name}(...)";
                sb.AppendLine(hint);
                continue;
            }

            sb.AppendLine($"        _instance.{prop.Name} = {defaultExpr};");
            any = true;
        }

        if (!any && schema.Properties.Count == 0)
            sb.AppendLine("        // schema has no properties");

        sb.AppendLine("    }");
        sb.AppendLine();
    }

    private static void AppendPropertyMethods(StringBuilder sb, string builder, SchemaPropertyDefinition prop)
    {
        switch (prop.Kind)
        {
            case PropertyKind.Array:
                AppendArrayMethods(sb, builder, prop);
                break;

            case PropertyKind.Object:
                sb.AppendLine($"    public {builder} With{prop.Name}({prop.ClrType} value)");
                sb.AppendLine("    {");
                sb.AppendLine($"        _instance.{prop.Name} = value;");
                sb.AppendLine("        return this;");
                sb.AppendLine("    }");
                sb.AppendLine();
                sb.AppendLine($"    /// <summary>Configures {prop.Name} through its own builder (nested DTO).</summary>");
                sb.AppendLine($"    public {builder} With{prop.Name}(Action<{prop.ClrType}Builder> configure)");
                sb.AppendLine("    {");
                sb.AppendLine($"        var nested = new {prop.ClrType}Builder();");
                sb.AppendLine("        configure(nested);");
                sb.AppendLine($"        _instance.{prop.Name} = nested.Build();");
                sb.AppendLine("        return this;");
                sb.AppendLine("    }");
                break;

            default:
                sb.AppendLine($"    public {builder} With{prop.Name}({prop.ClrType} value)");
                sb.AppendLine("    {");
                sb.AppendLine($"        _instance.{prop.Name} = value;");
                sb.AppendLine("        return this;");
                sb.AppendLine("    }");
                break;
        }
    }

    private static void AppendArrayMethods(StringBuilder sb, string builder, SchemaPropertyDefinition prop)
    {
        var element = prop.ClrType;
        var singular = Singular(prop.Name);

        sb.AppendLine($"    public {builder} With{prop.Name}(List<{element}> value)");
        sb.AppendLine("    {");
        sb.AppendLine($"        _instance.{prop.Name} = value;");
        sb.AppendLine("        return this;");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine($"    public {builder} Add{singular}({element} value)");
        sb.AppendLine("    {");
        sb.AppendLine($"        _instance.{prop.Name}.Add(value);");
        sb.AppendLine("        return this;");
        sb.AppendLine("    }");

        if (prop.ElementKind == PropertyKind.Object)
        {
            sb.AppendLine();
            sb.AppendLine($"    /// <summary>Adds a {element} configured through its own builder (nested DTO in a collection).</summary>");
            sb.AppendLine($"    public {builder} Add{singular}(Action<{element}Builder> configure)");
            sb.AppendLine("    {");
            sb.AppendLine($"        var nested = new {element}Builder();");
            sb.AppendLine("        configure(nested);");
            sb.AppendLine($"        _instance.{prop.Name}.Add(nested.Build());");
            sb.AppendLine("        return this;");
            sb.AppendLine("    }");
        }

        sb.AppendLine();
        sb.AppendLine($"    public {builder} Clear{prop.Name}()");
        sb.AppendLine("    {");
        sb.AppendLine($"        _instance.{prop.Name}.Clear();");
        sb.AppendLine("        return this;");
        sb.AppendLine("    }");
    }

    /// <summary>
    /// Bogus default expression for a property, driven by name/type heuristics.
    /// Returns null when there is no safe default (ids, collections).
    /// </summary>
    private static string? GetDefaultExpression(string schemaName, SchemaPropertyDefinition prop)
    {
        switch (prop.Kind)
        {
            case PropertyKind.Enum:
                return $"Faker.PickRandom<{prop.ClrType}>()";

            case PropertyKind.Object:
                return $"new {prop.ClrType}Builder().Build()";

            case PropertyKind.Array:
                // Collections start empty — element defaults (e.g. product ids)
                // cannot be guessed; tests add entries explicitly.
                return null;
        }

        var name = prop.JsonName.ToLowerInvariant();
        var inProductContext = schemaName.Contains("Product", StringComparison.OrdinalIgnoreCase)
                            || name.Contains("product");

        return prop.ClrType switch
        {
            "string" when name.Contains("email") || prop.Format == "email" => "Faker.Internet.Email()",
            "string" when name.Contains("password") => "\"TestPass123!\"",
            "string" when name.Contains("username") => "Faker.Internet.UserName() + Faker.Random.Number(1000, 9999)",
            "string" when name.EndsWith("name") && inProductContext => "Faker.Commerce.ProductName()",
            "string" when name.EndsWith("name") => "Faker.Name.FullName()",
            "string" when name.Contains("description") => "Faker.Commerce.ProductDescription()",
            "string" when name.Contains("street") => "Faker.Address.StreetAddress()",
            "string" when name.Contains("city") => "Faker.Address.City()",
            "string" when name.Contains("postal") || name.Contains("zip") => "Faker.Address.ZipCode()",
            "string" when name.Contains("country") => "Faker.Address.Country()",
            "string" when name.Contains("category") => "Faker.Commerce.Categories(1)[0]",
            "string" when name.Contains("note") => "Faker.Lorem.Sentence()",
            "string" when name.Contains("phone") => "Faker.Phone.PhoneNumber()",
            "string" when name.Contains("role") => "\"User\"",
            "string" => "Faker.Lorem.Word()",

            "int" when name.EndsWith("id") => null, // ids must come from the test
            "int" when name.Contains("stock") => "Faker.Random.Int(20, 500)",
            "int" when name.Contains("quantity") => "Faker.Random.Int(1, 5)",
            "int" => "Faker.Random.Int(1, 100)",
            "long" => "Faker.Random.Long(1, 100)",

            "decimal" when name.Contains("price") || name.Contains("amount")
                => "Math.Round(Faker.Random.Decimal(1, 999), 2)",
            "decimal" => "Math.Round(Faker.Random.Decimal(1, 999), 2)",

            "bool" => "true",
            "DateTimeOffset" => "DateTimeOffset.UtcNow",
            _ => null
        };
    }

    private static string Singular(string name)
    {
        if (name.EndsWith("ies", StringComparison.Ordinal))
            return name[..^3] + "y";
        if (name.EndsWith("s", StringComparison.Ordinal) && name.Length > 1)
            return name[..^1];
        return name + "Entry";
    }
}
