using Microsoft.OpenApi.Any;
using Microsoft.OpenApi.Models;
using System.Text;

namespace ApiTestFramework.OpenApi.Generator;

/// <summary>
/// Generates a C# DTO file from the <c>components/schemas</c> section of an OpenAPI document.
///
/// Handles:
///   • Object schemas  → public classes with auto-properties and sensible defaults
///   • String/integer enums → int-based C# enums (matches .NET JSON default serialisation)
///   • $ref / oneOf-with-single-ref → type-name reference
///   • Nullable properties → appends <c>?</c>
///   • Default string/integer/boolean values
///   • <c>date-time</c> format → <c>DateTimeOffset</c>
///   • <c>array</c> items → <c>List&lt;T&gt;</c>
///   • Skip list — omit schemas that live in a shared/common file
///   • Optional common-namespace using directive when shared types are referenced
/// </summary>
public static class DtoGenerator
{
    /// <summary>
    /// Generates a single C# source file containing all DTO classes and enums
    /// derived from <paramref name="document"/>'s component schemas.
    /// </summary>
    /// <param name="document">Parsed OpenAPI document.</param>
    /// <param name="namespaceName">Target C# namespace, e.g. <c>ApiTestFramework.Clients.ProductService</c>.</param>
    /// <param name="skipSchemas">
    ///   Schema names to omit from output (e.g. shared types defined in a common namespace).
    /// </param>
    /// <param name="commonNamespace">
    ///   When non-null, a <c>using</c> directive is added for this namespace so that
    ///   skipped / shared types can be referenced.
    /// </param>
    public static string GenerateDtoFile(
        OpenApiDocument document,
        string namespaceName,
        IReadOnlySet<string>? skipSchemas = null,
        string? commonNamespace = null)
    {
        var schemas = document.Components?.Schemas
            ?? new Dictionary<string, OpenApiSchema>();

        // Pre-compute enum names so class-property initialisers can distinguish
        // $ref-to-enum (no init needed) from $ref-to-class (= new()).
        var enumNames = new HashSet<string>(
            schemas.Where(kv => IsEnumSchema(kv.Value)).Select(kv => kv.Key),
            StringComparer.Ordinal);

        var sb = new StringBuilder();
        sb.AppendLine("// Auto-generated by ApiTestFramework.OpenApi.Generator.DtoGenerator");
        sb.AppendLine($"// Generated : {DateTime.UtcNow:yyyy-MM-dd HH:mm:ss} UTC");
        sb.AppendLine("// DO NOT EDIT — regenerate via generate-dtos.bat");
        sb.AppendLine();
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        // Add using for shared namespace when any skipped schema is actually referenced
        bool needsCommonNs = commonNamespace is not null
            && skipSchemas is not null
            && schemas
                .Where(kv => skipSchemas?.Contains(kv.Key) != true)
                .Any(kv => ReferencesAnySkipped(kv.Value, skipSchemas!));

        if (needsCommonNs)
            sb.AppendLine($"using {commonNamespace};");

        sb.AppendLine();
        sb.AppendLine($"namespace {namespaceName};");
        sb.AppendLine();

        foreach (var (name, schema) in schemas)
        {
            if (skipSchemas?.Contains(name) == true)
                continue;

            if (IsEnumSchema(schema))
                EmitEnum(sb, name, schema);
            else
                EmitClass(sb, name, schema, enumNames);
        }

        return sb.ToString().TrimEnd() + Environment.NewLine;
    }

    // ── schema detection ───────────────────────────────────────────────────────

    private static bool IsEnumSchema(OpenApiSchema schema) =>
        schema.Enum is { Count: > 0 };

    private static bool ReferencesAnySkipped(OpenApiSchema schema, IReadOnlySet<string> skipped)
    {
        if (schema.Properties == null) return false;
        foreach (var prop in schema.Properties.Values)
        {
            if (prop.Reference?.Id is { } id && skipped.Contains(id)) return true;
            if (prop.OneOf?.Any(o => o.Reference?.Id is { } rid && skipped.Contains(rid)) == true) return true;
        }
        return false;
    }

    // ── enum emission ──────────────────────────────────────────────────────────

    private static void EmitEnum(StringBuilder sb, string name, OpenApiSchema schema)
    {
        sb.AppendLine($"public enum {name}");
        sb.AppendLine("{");

        for (int i = 0; i < schema.Enum.Count; i++)
        {
            var memberName = schema.Enum[i] switch
            {
                OpenApiString s  => s.Value,
                OpenApiInteger v => v.Value.ToString(),
                var other        => other.ToString() ?? $"Value{i}"
            };
            sb.AppendLine($"    {memberName} = {i},");
        }

        sb.AppendLine("}");
        sb.AppendLine();
    }

    // ── class emission ─────────────────────────────────────────────────────────

    private static void EmitClass(StringBuilder sb, string name, OpenApiSchema schema,
        HashSet<string> enumNames)
    {
        sb.AppendLine($"public class {name}");
        sb.AppendLine("{");

        foreach (var (propName, propSchema) in schema.Properties
                     ?? new Dictionary<string, OpenApiSchema>())
        {
            var pascalName  = ToPascalCase(propName);
            var (csType, defaultInit) = ResolveProperty(propSchema);

            if (propSchema.Nullable && !csType.EndsWith("?"))
                csType += "?";

            var init = defaultInit ?? ImpliedInit(csType, propSchema.Nullable, enumNames);
            var tail = init is null ? "" : $" = {init};";

            sb.AppendLine($"    public {csType} {pascalName} {{ get; set; }}{tail}");
        }

        sb.AppendLine("}");
        sb.AppendLine();
    }

    // ── type resolution ────────────────────────────────────────────────────────

    /// <summary>Returns (C# type name, optional initialiser expression).</summary>
    private static (string type, string? init) ResolveProperty(OpenApiSchema schema)
    {
        // Direct $ref → named type
        if (schema.Reference is not null)
            return (schema.Reference.Id, null);

        // oneOf with a single $ref (used for nullable enum references)
        if (schema.OneOf?.Count == 1 && schema.OneOf[0].Reference is not null)
            return (schema.OneOf[0].Reference.Id, null);

        // Array
        if (schema.Type == "array")
        {
            var itemType = schema.Items?.Reference?.Id ?? MapScalar(schema.Items);
            return ($"List<{itemType}>", "new()");
        }

        // Scalar + optional default
        var csType = MapScalar(schema);
        string? initExpr = null;

        if (schema.Default is OpenApiString   ds) initExpr = $"\"{ds.Value}\"";
        else if (schema.Default is OpenApiInteger di) initExpr = di.Value.ToString();
        else if (schema.Default is OpenApiBoolean db) initExpr = db.Value ? "true" : "false";

        return (csType, initExpr);
    }

    private static string MapScalar(OpenApiSchema? schema) =>
        (schema?.Type, schema?.Format) switch
        {
            ("string",  "date-time") => "DateTimeOffset",
            ("string",  _)           => "string",
            ("integer", "int64")     => "long",
            ("integer", _)           => "int",
            ("number",  "float")     => "float",
            ("number",  "double")    => "double",
            ("number",  _)           => "decimal",
            ("boolean", _)           => "bool",
            _                        => "object"
        };

    /// <summary>
    /// Returns a sensible default initialiser so properties are never null after construction,
    /// unless the property is explicitly nullable.
    /// </summary>
    private static string? ImpliedInit(string csType, bool nullable, HashSet<string> enumNames)
    {
        if (nullable) return null;

        return csType switch
        {
            "string"        => "string.Empty",
            "DateTimeOffset" => null,   // default(DateTimeOffset) is fine
            "int"    or "long" or "decimal"
                     or "float" or "double" or "bool" => null,
            "object" => null,
            var t when t.EndsWith("?") => null,
            // Enums have a zero-value default — no init needed
            var t when enumNames.Contains(t) => null,
            // Anything else (nested class reference, List<T>) gets new()
            _ => "new()"
        };
    }

    // ── helpers ────────────────────────────────────────────────────────────────

    private static string ToPascalCase(string value) =>
        string.IsNullOrEmpty(value) ? value
            : char.ToUpperInvariant(value[0]) + value[1..];
}
