using ApiTestFramework.OpenApi.Models;
using System.Text;

namespace ApiTestFramework.OpenApi.Generator;

/// <summary>
/// Generates a complete *ServiceSteps.cs file from parsed OpenAPI endpoints.
///
/// The output mirrors the hand-written step classes in ApiTestFramework.Steps:
///   • Constructor resolves <c>ApiClient</c> from <c>ContainerProvider</c>.
///   • Each endpoint gets a happy-path method (typed <c>RestResponse&lt;T&gt;</c>).
///   • POST/PUT/DELETE also get a matching <c>Try*Async</c> raw-response overload.
///   • Every method is annotated with <c>[AllureStep]</c>.
/// </summary>
public static class StepsGenerator
{
    /// <summary>
    /// Generates C# source for a steps class from a list of endpoint definitions.
    /// </summary>
    /// <param name="endpoints">Parsed endpoints from <see cref="OpenApiSpecLoader"/>.</param>
    /// <param name="serviceName">
    ///   e.g. "Product" — used to build class name (<c>ProductServiceSteps</c>),
    ///   namespace, client name (<c>"ProductService"</c>), and route class (<c>ProductServiceRoutes</c>).
    /// </param>
    /// <param name="responseDto">
    ///   Fully-qualified or simple type name for the primary response DTO,
    ///   e.g. "Product".  List endpoints use <c>List&lt;responseDto&gt;</c>.
    /// </param>
    /// <param name="namespaceName">Target C# namespace for the generated file.</param>
    /// <param name="dtoNamespace">
    ///   Namespace that contains <paramref name="responseDto"/> and request DTOs,
    ///   e.g. "ApiTestFramework.Clients.ProductService".
    /// </param>
    public static string GenerateStepsClass(
        IReadOnlyList<EndpointDefinition> endpoints,
        string serviceName,
        string responseDto,
        string namespaceName,
        string dtoNamespace)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// Auto-generated by ApiTestFramework.OpenApi.Generator.StepsGenerator");
        sb.AppendLine($"// Generated : {DateTime.UtcNow:yyyy-MM-dd HH:mm:ss} UTC");
        sb.AppendLine($"// Service   : {serviceName}");
        sb.AppendLine("// DO NOT EDIT — regenerate via generate-steps.bat");
        sb.AppendLine();
        sb.AppendLine("using System.Net;");
        sb.AppendLine("using Allure.NUnit.Attributes;");
        sb.AppendLine($"using {dtoNamespace};");
        sb.AppendLine("using ApiTestFramework.Core.Assertions;");
        sb.AppendLine("using ApiTestFramework.Core.Client;");
        sb.AppendLine("using ApiTestFramework.Core.Constants;");
        sb.AppendLine("using ApiTestFramework.Core.DI;");
        sb.AppendLine("using RestSharp;");
        sb.AppendLine("using Serilog;");
        sb.AppendLine();
        sb.AppendLine($"namespace {namespaceName};");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine($"/// Auto-generated step class for {serviceName}Service operations.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine($"public class {serviceName}ServiceSteps");
        sb.AppendLine("{");
        sb.AppendLine("    private readonly ApiClient _client;");
        sb.AppendLine("    private readonly ILogger _logger;");
        sb.AppendLine();
        sb.AppendLine($"    public {serviceName}ServiceSteps()");
        sb.AppendLine("    {");
        sb.AppendLine($"        _client = ContainerProvider.ResolveNamed<ApiClient>(\"{serviceName}Service\");");
        sb.AppendLine($"        _logger = Log.ForContext<{serviceName}ServiceSteps>();");
        sb.AppendLine("    }");

        // Group endpoints by tag / path to emit one method per operation
        foreach (var ep in endpoints)
        {
            var methodName = BuildMethodName(ep);
            var allureLabel = BuildAllureLabel(ep);
            var returnType = InferReturnType(ep, responseDto);
            var innerType = responseDto; // always single-item type for SendAsync<T>
            var isVoidResponse = ep.Method == "DELETE" && !ep.Responses.ContainsKey(200);

            sb.AppendLine();
            sb.AppendLine("    /// <summary>");
            sb.AppendLine($"    /// {ep.Method} {ep.Path}");
            if (ep.RequiresAuth)
                sb.AppendLine("    /// Requires Bearer token.");
            sb.AppendLine("    /// </summary>");
            sb.AppendLine($"    [AllureStep(\"{allureLabel}\")]");

            if (isVoidResponse)
            {
                // void response (DELETE returning 204)
                sb.AppendLine($"    public async Task<RestResponse> {methodName}Async({BuildParams(ep)})");
                sb.AppendLine("    {");
                AppendRequestBody(sb, ep, innerType);
                sb.AppendLine("        return response;");
                sb.AppendLine("    }");
            }
            else
            {
                // typed response — happy-path method that asserts 2xx
                var successCode = ep.Responses.Keys.FirstOrDefault(k => k is >= 200 and < 300);
                var httpStatusConst = successCode == 201 ? "HttpStatusCode.Created" : "HttpStatusCode.OK";

                sb.AppendLine($"    public async Task<{returnType}> {methodName}Async({BuildParams(ep)})");
                sb.AppendLine("    {");
                AppendRequestBody(sb, ep, returnType);
                sb.AppendLine($"        response.ShouldHaveStatusCode({httpStatusConst});");
                sb.AppendLine($"        return response.ShouldHaveData();");
                sb.AppendLine("    }");

                // Try* overload for mutating verbs
                if (ep.Method is "POST" or "PUT" or "DELETE")
                {
                    sb.AppendLine();
                    sb.AppendLine("    /// <summary>");
                    sb.AppendLine($"    /// Raw-response overload for {ep.Method} {ep.Path}.");
                    sb.AppendLine("    /// Use for negative test scenarios (validation errors, auth failures).");
                    sb.AppendLine("    /// </summary>");
                    sb.AppendLine($"    [AllureStep(\"Attempt: {allureLabel} (raw response)\")]");
                    sb.AppendLine($"    public async Task<RestResponse<{returnType}>> Try{methodName}Async({BuildParams(ep)})");
                    sb.AppendLine("    {");
                    AppendRequestBodyRaw(sb, ep, returnType);
                    sb.AppendLine("        return response;");
                    sb.AppendLine("    }");
                }
            }
        }

        sb.AppendLine("}");
        return sb.ToString();
    }

    // ── private helpers ────────────────────────────────────────────────────────

    private static string BuildMethodName(EndpointDefinition ep)
    {
        // OperationId is already PascalCase in most OpenAPI specs; strip trailing "Async"
        var name = ep.OperationId;
        if (string.IsNullOrWhiteSpace(name))
        {
            // fallback: verb + resource derived from path
            var resource = ep.Path.Split('/').LastOrDefault(s => !s.StartsWith('{'))
                           ?? "Resource";
            name = $"{ToPascalCase(ep.Method.ToLowerInvariant())}{ToPascalCase(resource)}";
        }
        name = name.EndsWith("Async", StringComparison.OrdinalIgnoreCase)
            ? name[..^5]
            : name;
        return ToPascalCase(name);
    }

    private static string BuildAllureLabel(EndpointDefinition ep)
    {
        var idParam = ep.Parameters.FirstOrDefault(p => p.In == "path" && p.Name.Equals("id", StringComparison.OrdinalIgnoreCase));
        return idParam is not null
            ? $"{ep.Method} {ep.Path.Replace("{id}", "{id}")}: {{id}}"
            : $"{ep.Method} {ep.Path}";
    }

    private static string InferReturnType(EndpointDefinition ep, string responseDto)
    {
        // GET /collection → List<T>; everything else → T
        var isCollection = ep.Method == "GET" && !ep.Path.TrimEnd('/').EndsWith('}');
        return isCollection ? $"List<{responseDto}>" : responseDto;
    }

    private static string BuildParams(EndpointDefinition ep)
    {
        var parts = new List<string>();

        // Path parameters
        foreach (var p in ep.Parameters.Where(p => p.In == "path"))
            parts.Add($"{MapType(p.Type)} {p.Name}");

        // Query parameters
        foreach (var p in ep.Parameters.Where(p => p.In == "query"))
            parts.Add($"{MapType(p.Type)} {p.Name}");

        // Request body
        if (ep.RequestBodySchema is not null)
            parts.Add($"{ep.RequestBodySchema} request");

        return string.Join(", ", parts);
    }

    private static void AppendRequestBody(StringBuilder sb, EndpointDefinition ep, string responseDto)
    {
        sb.AppendLine($"        var response = await _client.SendAsync<{responseDto}>(");
        sb.AppendLine($"            {BuildRequestExpression(ep)});");
    }

    private static void AppendRequestBodyRaw(StringBuilder sb, EndpointDefinition ep, string responseDto)
    {
        sb.AppendLine($"        var response = await _client.SendAsync<{responseDto}>(");
        sb.AppendLine($"            {BuildRequestExpression(ep)});");
    }

    private static string BuildRequestExpression(EndpointDefinition ep)
    {
        var hasPathParam = ep.Parameters.Any(p => p.In == "path");
        var hasBody = ep.RequestBodySchema is not null;
        var hasQuery = ep.Parameters.Any(p => p.In == "query");

        var restMethod = ep.Method switch
        {
            "GET"    => "Method.Get",
            "POST"   => "Method.Post",
            "PUT"    => "Method.Put",
            "DELETE" => "Method.Delete",
            "PATCH"  => "Method.Patch",
            _        => "Method.Get"
        };

        if (!hasPathParam && !hasQuery && !hasBody)
        {
            return ep.Method == "GET"
                ? $"RequestFactory.Get(\"{ep.Path}\")"
                : $"RequestFactory.{ToPascalCase(ep.Method.ToLowerInvariant())}(\"{ep.Path}\", request)";
        }

        var lines = new List<string>
        {
            "RequestBuilder.Create()",
            $"                .WithMethod({restMethod})",
            $"                .WithPath(\"{ep.Path}\")"
        };

        foreach (var p in ep.Parameters.Where(p => p.In == "path"))
            lines.Add($"                .WithPathSegment(\"{p.Name}\", {p.Name})");

        foreach (var p in ep.Parameters.Where(p => p.In == "query"))
            lines.Add($"                .WithQueryParameter(\"{p.Name}\", {p.Name})");

        if (hasBody)
            lines.Add("                .WithBody(request)");

        return string.Join("\n            ", lines);
    }

    private static string MapType(string openApiType) => openApiType switch
    {
        "integer" => "int",
        "number"  => "decimal",
        "boolean" => "bool",
        _         => "string"
    };

    private static string ToPascalCase(string value)
    {
        if (string.IsNullOrEmpty(value)) return value;
        return char.ToUpperInvariant(value[0]) + value[1..];
    }
}
