using ApiTestFramework.OpenApi.Models;
using System.Text;

namespace ApiTestFramework.OpenApi.Generator;

/// <summary>
/// Defines a single test case derived from an OpenAPI endpoint.
/// </summary>
public record TestCaseDefinition(
    string TestName,
    string ServiceName,
    EndpointDefinition Endpoint,
    TestScenario Scenario,
    int ExpectedStatusCode,
    string Description);

public enum TestScenario
{
    HappyPath,
    NotFound,
    Unauthorized,
    BadRequest,
    Conflict
}

/// <summary>
/// Generates <see cref="TestCaseDefinition"/> objects from parsed OpenAPI endpoints,
/// and can optionally render them as C# test class stubs.
/// </summary>
public static class TestCaseScaffolder
{
    /// <summary>
    /// Generates test case definitions for each endpoint covering:
    /// happy path, auth, not-found (id-based), and bad-request (POST/PUT) scenarios.
    /// </summary>
    public static IReadOnlyList<TestCaseDefinition> GenerateTestCases(
        IReadOnlyList<EndpointDefinition> endpoints,
        string serviceName)
    {
        var cases = new List<TestCaseDefinition>();

        foreach (var endpoint in endpoints)
        {
            // Happy path — first 2xx response
            var successCode = endpoint.Responses.Keys.FirstOrDefault(k => k is >= 200 and < 300);
            if (successCode > 0)
            {
                cases.Add(new TestCaseDefinition(
                    TestName: BuildTestName(endpoint, TestScenario.HappyPath),
                    ServiceName: serviceName,
                    Endpoint: endpoint,
                    Scenario: TestScenario.HappyPath,
                    ExpectedStatusCode: successCode,
                    Description: $"{endpoint.Method} {endpoint.Path} — returns {successCode}"));
            }

            // Unauthorized — endpoint requires auth
            if (endpoint.RequiresAuth)
            {
                cases.Add(new TestCaseDefinition(
                    TestName: BuildTestName(endpoint, TestScenario.Unauthorized),
                    ServiceName: serviceName,
                    Endpoint: endpoint,
                    Scenario: TestScenario.Unauthorized,
                    ExpectedStatusCode: 401,
                    Description: $"{endpoint.Method} {endpoint.Path} without token — returns 401"));
            }

            // Not Found — endpoints with path parameter {id}
            if (endpoint.Path.Contains("{id", StringComparison.OrdinalIgnoreCase)
                && endpoint.Method != "POST")
            {
                cases.Add(new TestCaseDefinition(
                    TestName: BuildTestName(endpoint, TestScenario.NotFound),
                    ServiceName: serviceName,
                    Endpoint: endpoint,
                    Scenario: TestScenario.NotFound,
                    ExpectedStatusCode: 404,
                    Description: $"{endpoint.Method} {endpoint.Path} with invalid id — returns 404"));
            }

            // Bad Request — POST/PUT with request body
            if (endpoint.Method is "POST" or "PUT" && endpoint.RequestBodySchema is not null)
            {
                cases.Add(new TestCaseDefinition(
                    TestName: BuildTestName(endpoint, TestScenario.BadRequest),
                    ServiceName: serviceName,
                    Endpoint: endpoint,
                    Scenario: TestScenario.BadRequest,
                    ExpectedStatusCode: 400,
                    Description: $"{endpoint.Method} {endpoint.Path} with invalid body — returns 400"));
            }
        }

        return cases;
    }

    /// <summary>
    /// Renders a list of test case definitions as a C# test class stub.
    /// Each test body is marked as <c>Assert.Inconclusive</c> until implemented.
    /// </summary>
    public static string GenerateCSharpTestClass(
        IReadOnlyList<TestCaseDefinition> testCases,
        string namespaceName)
    {
        if (testCases.Count == 0) return string.Empty;

        var serviceName = testCases[0].ServiceName;
        var sb = new StringBuilder();
        sb.AppendLine("// Auto-generated by ApiTestFramework.OpenApi.Generator");
        sb.AppendLine($"// Generated: {DateTime.UtcNow:yyyy-MM-dd HH:mm:ss} UTC");
        sb.AppendLine($"// Source: OpenAPI spec for {serviceName}");
        sb.AppendLine("// DO NOT EDIT — regenerate via TestCaseScaffolder");
        sb.AppendLine();
        sb.AppendLine("using System.Net;");
        sb.AppendLine("using NUnit.Framework;");
        sb.AppendLine("using ApiTestFramework.Core.Base;");
        sb.AppendLine("using ApiTestFramework.Core.Assertions;");
        sb.AppendLine();
        sb.AppendLine($"namespace {namespaceName};");
        sb.AppendLine();
        sb.AppendLine("[TestFixture]");
        sb.AppendLine($"public class {serviceName}GeneratedTests : BaseTest");
        sb.AppendLine("{");

        foreach (var tc in testCases)
        {
            sb.AppendLine($"    [Test]");
            sb.AppendLine($"    [Description(\"{tc.Description}\")]");
            sb.AppendLine($"    [Category(\"{tc.Scenario}\")]");
            sb.AppendLine($"    public async Task {tc.TestName}()");
            sb.AppendLine("    {");
            sb.AppendLine($"        // Endpoint : {tc.Endpoint.Method} {tc.Endpoint.Path}");
            sb.AppendLine($"        // Scenario : {tc.Scenario}");
            sb.AppendLine($"        // Expected : HTTP {tc.ExpectedStatusCode}");
            sb.AppendLine("        await Task.CompletedTask;");
            sb.AppendLine("        Assert.Inconclusive(\"Scaffold only — implement test body.\");");
            sb.AppendLine("    }");
            sb.AppendLine();
        }

        sb.AppendLine("}");
        return sb.ToString();
    }

    private static string BuildTestName(EndpointDefinition endpoint, TestScenario scenario)
    {
        var resource = ToPascalCase(endpoint.OperationId);
        var scenarioSuffix = scenario switch
        {
            TestScenario.HappyPath    => "ReturnsSuccess",
            TestScenario.NotFound     => "WithInvalidId_ReturnsNotFound",
            TestScenario.Unauthorized => "WithoutToken_ReturnsUnauthorized",
            TestScenario.BadRequest   => "WithInvalidBody_ReturnsBadRequest",
            TestScenario.Conflict     => "WithDuplicate_ReturnsConflict",
            _                         => "Unknown"
        };
        return $"{resource}_{scenarioSuffix}";
    }

    private static string ToPascalCase(string value)
    {
        if (string.IsNullOrEmpty(value)) return value;
        return char.ToUpperInvariant(value[0]) + value[1..];
    }
}
