using ApiTestFramework.OpenApi.Generator;
using ApiTestFramework.OpenApi.Loader;
using FluentAssertions;
using NUnit.Framework;

namespace ApiTestFramework.OpenApi.Tests;

[TestFixture]
public class BuilderScaffolderTests
{
    private IReadOnlyDictionary<string, string> _files = null!;

    [OneTimeSetUp]
    public void Generate()
    {
        var document = FixtureLoader.LoadWidgetSwagger();
        var schemas = SchemaExtractor.GetRequestSchemas(document);
        _files = BuilderScaffolder.GenerateBuilders(
            schemas,
            dtoNamespace: "Test.Dtos",
            builderNamespace: "Test.Builders",
            sourceName: "widget-swagger.json");
    }

    [Test]
    public void GeneratesOneBuilderPerObjectSchema_NoneForEnums()
    {
        _files.Keys.Should().BeEquivalentTo(
            "CreateWidgetRequestBuilder.g.cs",
            "DetailsRequestBuilder.g.cs",
            "PartRequestBuilder.g.cs");
    }

    [Test]
    public void BuilderIsPartialWithHooks()
    {
        var code = _files["CreateWidgetRequestBuilder.g.cs"];
        code.Should().Contain("public partial class CreateWidgetRequestBuilder");
        code.Should().Contain("partial void OnDefaultsApplied();");
        code.Should().Contain("partial void OnBeforeBuild(CreateWidgetRequest instance);");
    }

    [Test]
    public void NestedObjectGetsBuilderActionOverload()
    {
        var code = _files["CreateWidgetRequestBuilder.g.cs"];
        code.Should().Contain("WithDetails(Action<DetailsRequestBuilder> configure)");
        code.Should().Contain("WithDetails(DetailsRequest value)");
    }

    [Test]
    public void ArrayOfObjectsGetsAddAndClearMethods()
    {
        var code = _files["CreateWidgetRequestBuilder.g.cs"];
        code.Should().Contain("AddPart(PartRequest value)");
        code.Should().Contain("AddPart(Action<PartRequestBuilder> configure)");
        code.Should().Contain("ClearParts()");
        code.Should().Contain("WithParts(List<PartRequest> value)");
    }

    [Test]
    public void EmailHeuristicUsesBogusInternetEmail()
    {
        _files["CreateWidgetRequestBuilder.g.cs"]
            .Should().Contain("_instance.ContactEmail = Faker.Internet.Email();");
    }

    [Test]
    public void IdPropertiesGetNoDefault()
    {
        DefaultsSection(_files["CreateWidgetRequestBuilder.g.cs"])
            .Should().NotContain("_instance.OwnerId =",
                "ids must be provided by the test, never invented");
        _files["CreateWidgetRequestBuilder.g.cs"]
            .Should().Contain("// OwnerId: no safe default");

        DefaultsSection(_files["PartRequestBuilder.g.cs"])
            .Should().NotContain("_instance.PartId =");
    }

    [Test]
    public void EnumDefaultUsesPickRandom()
    {
        _files["CreateWidgetRequestBuilder.g.cs"]
            .Should().Contain("_instance.Status = Faker.PickRandom<WidgetStatus>();");
    }

    [Test]
    public void NullableOptionalPropertiesGetNoDefault()
    {
        _files["CreateWidgetRequestBuilder.g.cs"]
            .Should().NotContain("_instance.Details = new DetailsRequestBuilder",
                "optional nullable nested objects stay null by default");
    }

    [Test]
    public void CollectionsStartEmpty()
    {
        var code = _files["CreateWidgetRequestBuilder.g.cs"];
        code.Should().Contain("// Parts: starts empty");
        DefaultsSection(code).Should().NotContain("_instance.Parts =");
    }

    /// <summary>The ApplyDefaults() body — With* setters also assign to _instance,
    /// so default-related assertions must be scoped to this section.</summary>
    private static string DefaultsSection(string code)
    {
        var start = code.IndexOf("private void ApplyDefaults()", StringComparison.Ordinal);
        var end = code.IndexOf("// Partial hooks", StringComparison.Ordinal);
        return code[start..end];
    }

    [Test]
    public void GeneratedFileCarriesAutoGeneratedHeader()
    {
        _files.Values.Should().OnlyContain(code =>
            code.Contains("<auto-generated>") && code.Contains("do not edit by hand"));
    }
}
