#!/usr/bin/env python3
"""
Generate k6 load-test scripts from the committed OpenAPI specs.

Usage:
    python3 tools/generate_k6.py

Output (perf/k6/):
    product-service.js   — CRUD load scenario for ProductService
    order-service.js     — CRUD load scenario for OrderService (seeds a product)
    auth-service.js      — register/login scenario for AuthService
    all-services.js      — combined scenario exercising everything

Run (requires k6 — https://k6.io):
    k6 run perf/k6/product-service.js                         # smoke profile
    k6 run -e PROFILE=load perf/k6/all-services.js            # 20 VUs ramp
    k6 run -e PROFILE=stress -e AUTH_BASE_URL=http://host:5300 perf/k6/order-service.js

Profiles (selectable via -e PROFILE=...):
    smoke  —  2 VUs, 30s          (default; CI-friendly sanity check)
    load   — ramp to 20 VUs, 3m   (normal expected traffic)
    stress — ramp to 100 VUs, 6m  (find the breaking point)

Each script:
  - registers a unique user in setup() and reuses the JWT for all VUs
  - chains CRUD flows (create → read → update → delete) with per-endpoint checks
  - resolves cross-service foreign keys (e.g. order.productId → creates a product)
  - enforces thresholds: p95 latency and error-rate budgets
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from openapi_common import (  # noqa: E402
    REPO_ROOT, SERVICES, Endpoint, Service,
    crud_sort_key, discover_auth_flow, example_body, example_param_value,
    foreign_key_resource, load_all, resource_of, singular,
)

K6_DIR = REPO_ROOT / "perf" / "k6"

HEADER = """\
// Auto-generated by tools/generate_k6.py — DO NOT EDIT, regenerate instead.
// Source: OpenAPI specs in tests/ApiTestFramework.Clients/swagger/
import http from 'k6/http';
import { check, group, sleep } from 'k6';
import { Rate } from 'k6/metrics';
"""

PROFILES_JS = """\
const PROFILES = {
  smoke:  { vus: 2, duration: '30s' },
  load:   { stages: [ { duration: '30s', target: 20 }, { duration: '2m', target: 20 }, { duration: '30s', target: 0 } ] },
  stress: { stages: [ { duration: '1m', target: 25 }, { duration: '2m', target: 50 }, { duration: '2m', target: 100 }, { duration: '1m', target: 0 } ] },
};
const profile = PROFILES[__ENV.PROFILE || 'smoke'];

export const options = {
  ...profile,
  thresholds: {
    http_req_duration: ['p(95)<500'],
    checks: ['rate>0.99'],
    errors: ['rate<0.01'],
  },
};

const errorRate = new Rate('errors');
"""


def js_string(value: str) -> str:
    return json.dumps(value)


def base_url_const(service: Service) -> str:
    return f"{service.key.upper()}_BASE_URL"


def env_url_decl(service: Service) -> str:
    return (f"const {base_url_const(service)} = "
            f"__ENV.{service.env_var} || {js_string(service.default_base_url)};")


def auth_setup_js(auth_service: Service, token_path: list[str]) -> str:
    """JS for setup(): register a unique user, return the bearer token."""
    accessor = "".join(f".{p}" for p in token_path)
    return f"""\
function obtainToken() {{
  const uniq = `${{Date.now()}}_${{Math.floor(Math.random() * 1e6)}}`;
  const registerPayload = JSON.stringify({{
    username: `perf_user_${{uniq}}`,
    email: `perf_user_${{uniq}}@example.com`,
    password: 'P@ssw0rd_123!',
    role: 'User',
  }});
  const res = http.post(`${{{base_url_const(auth_service)}}}/api/auth/register`, registerPayload, {{
    headers: {{ 'Content-Type': 'application/json' }},
  }});
  if (res.status !== 201 && res.status !== 200) {{
    throw new Error(`auth setup failed: HTTP ${{res.status}} ${{res.body}}`);
  }}
  return res.json(){accessor};
}}
"""


def k6_path_expr(endpoint: Endpoint, spec: dict, id_var: str | None,
                 payload_var: str | None, create_payload: dict | None) -> str:
    """Build a JS template-literal path, substituting path params.

    {id}      → ${<id_var>} when a captured id is available
    {other}   → value from the create payload when a matching field exists,
                otherwise a literal example value.
    """
    path = endpoint.path
    for param in endpoint.path_params:
        name = param["name"]
        placeholder = "{" + name + "}"
        field = _payload_field_for(name, create_payload)
        if name.lower() == "id" and id_var:
            path = path.replace(placeholder, f"${{{id_var}}}")
        elif payload_var and field is not None:
            path = path.replace(placeholder, f"${{{payload_var}.{field}}}")
        else:
            path = path.replace(placeholder, str(example_param_value(spec, param)))
    return path


def _payload_field_for(param_name: str, payload: dict | None) -> str | None:
    """Find the create-payload field that corresponds to a path param
    ('category' → 'category', 'email' → 'customerEmail')."""
    if not payload:
        return None
    name = param_name.lower()
    for key in payload:
        if key.lower() == name:
            return key
    for key in payload:
        if name in key.lower():
            return key
    return None


def crud_flow_js(service: Service, spec: dict, endpoints: list[Endpoint],
                 fk_seeds: dict[str, str]) -> str:
    """Emit a group() per resource with a chained CRUD flow."""
    by_resource: dict[str, list[Endpoint]] = {}
    for ep in endpoints:
        by_resource.setdefault(resource_of(ep.path), []).append(ep)

    blocks: list[str] = []
    for resource, eps in by_resource.items():
        eps = sorted(eps, key=crud_sort_key)
        create_ep = next((e for e in eps if e.method == "POST"), None)
        lines: list[str] = [f"  group({js_string(resource + ' CRUD')}, () => {{"]
        id_var = None
        payload_var = None
        payload: dict | None = None

        if create_ep is not None:
            payload = example_body(spec, create_ep) or {}
            payload_var = "createPayload"
            payload_js = json.dumps(payload, indent=2)
            # splice seeded foreign keys (e.g. productId from setup data)
            for fk_field, js_expr in fk_seeds.items():
                if fk_field in payload:
                    payload_js = payload_js.replace(
                        f'"{fk_field}": {json.dumps(payload[fk_field])}',
                        f'"{fk_field}": {js_expr}')
            indented = "\n".join("    " + l for l in payload_js.splitlines())
            lines.append(f"    const {payload_var} = \n{indented};")

        for ep in eps:
            label = f"{ep.method} {ep.path}"
            expected = ep.success_status or 200
            path_expr = k6_path_expr(ep, spec, id_var, payload_var, payload)
            url = f"`${{{base_url_const(service)}}}{path_expr}`"
            var = "res"
            if ep.method == "POST":
                lines.append(
                    f"    let {var} = http.post({url}, "
                    f"JSON.stringify({payload_var}), params);")
            elif ep.method in ("PUT", "PATCH"):
                update_payload = json.dumps(example_body(spec, ep) or {})
                lines.append(
                    f"    {var} = http.{ep.method.lower()}({url}, "
                    f"JSON.stringify({update_payload}), params);")
            elif ep.method == "DELETE":
                lines.append(f"    {var} = http.del({url}, null, params);")
            else:
                lines.append(f"    {var} = http.get({url}, params);")

            lines.append(
                f"    check({var}, {{ {js_string(label + ' → ' + str(expected))}: "
                f"(r) => r.status === {expected} }}) || errorRate.add(1);")

            if ep.method == "POST" and id_var is None:
                id_var = f"{singular(resource)}Id"
                lines.append(f"    const {id_var} = {var}.json('id');")

        lines.append("    sleep(0.1);")
        lines.append("  });")
        blocks.append("\n".join(lines))

    return "\n\n".join(blocks)


def fk_seed_setup(service: Service, spec: dict, endpoints: list[Endpoint],
                  all_specs: list) -> tuple[str, dict[str, str]]:
    """For foreign-key fields (productId, ...) in this service's create payloads,
    emit setup() code that creates the dependency via its owning service.

    Returns (setup_js, {field_name: js_expression_reading_seeded_id})."""
    needed: dict[str, str] = {}
    for ep in endpoints:
        if ep.method != "POST":
            continue
        body = example_body(spec, ep) or {}
        for field_name in body:
            pool = foreign_key_resource(field_name)
            if pool:
                needed[field_name] = pool

    setup_lines: list[str] = []
    seeds: dict[str, str] = {}
    for field_name, pool in needed.items():
        for other_service, other_spec, other_eps in all_specs:
            create = next(
                (e for e in other_eps
                 if e.method == "POST" and resource_of(e.path) == pool), None)
            if create is None:
                continue
            seed_payload = json.dumps(example_body(other_spec, create) or {})
            setup_lines.append(f"""\
  // seed dependency: {field_name} ← {other_service.name} {create.method} {create.path}
  const seedRes_{field_name} = http.post(
    `${{{base_url_const(other_service)}}}{create.path}`,
    JSON.stringify({seed_payload}),
    {{ headers: {{ 'Content-Type': 'application/json', Authorization: `Bearer ${{token}}` }} }});
  if (seedRes_{field_name}.status !== {create.success_status or 201}) {{
    throw new Error(`failed to seed {field_name}: HTTP ${{seedRes_{field_name}.status}}`);
  }}
  data.{field_name} = seedRes_{field_name}.json('id');""")
            seeds[field_name] = f"data.{field_name}"
            break
    return "\n".join(setup_lines), seeds


def generate_service_script(service: Service, spec: dict, endpoints: list[Endpoint],
                            all_specs: list, auth_service: Service,
                            token_path: list[str]) -> str:
    url_decls = {env_url_decl(auth_service), env_url_decl(service)}
    setup_seed_js, seeds = fk_seed_setup(service, spec, endpoints, all_specs)
    # fk seeding may call other services — declare their URLs too
    for other_service, _, _ in all_specs:
        if base_url_const(other_service) in setup_seed_js:
            url_decls.add(env_url_decl(other_service))

    body = crud_flow_js(service, spec, endpoints, seeds)

    return f"""{HEADER}
{chr(10).join(sorted(url_decls))}

{PROFILES_JS}
{auth_setup_js(auth_service, token_path)}
export function setup() {{
  const token = obtainToken();
  const data = {{ token }};
{setup_seed_js}
  return data;
}}

export default function (data) {{
  const params = {{
    headers: {{
      'Content-Type': 'application/json',
      Authorization: `Bearer ${{data.token}}`,
    }},
  }};

{body}
}}
"""


def generate_auth_script(service: Service, spec: dict,
                         endpoints: list[Endpoint], token_path: list[str]) -> str:
    """Auth service is special: the scenario itself is register + login."""
    flow = discover_auth_flow(spec, endpoints)
    accessor = "".join(f".{p}" for p in token_path)
    reg = flow.register_endpoint
    login = flow.login_endpoint
    reg_status = (reg.success_status if reg else 201) or 201
    login_status = (login.success_status if login else 200) or 200
    return f"""{HEADER}
{env_url_decl(service)}

{PROFILES_JS}
export default function () {{
  const uniq = `${{__VU}}_${{__ITER}}_${{Date.now()}}`;
  const headers = {{ 'Content-Type': 'application/json' }};
  const username = `perf_user_${{uniq}}`;
  const password = 'P@ssw0rd_123!';

  group('register + login', () => {{
    const regRes = http.post(`${{{base_url_const(service)}}}{reg.path if reg else '/api/auth/register'}`,
      JSON.stringify({{ username, email: `${{username}}@example.com`, password, role: 'User' }}),
      {{ headers }});
    check(regRes, {{ {js_string(f'POST register → {reg_status}')}: (r) => r.status === {reg_status} }}) || errorRate.add(1);

    const loginRes = http.post(`${{{base_url_const(service)}}}{login.path if login else '/api/auth/login'}`,
      JSON.stringify({{ username, password }}),
      {{ headers }});
    const loginOk = check(loginRes, {{
      {js_string(f'POST login → {login_status}')}: (r) => r.status === {login_status},
      'login returns token': (r) => Boolean(r.json(){accessor}),
    }});
    if (!loginOk) errorRate.add(1);

    sleep(0.1);
  }});
}}
"""


def generate_combined_script(all_specs: list, auth_service: Service,
                             token_path: list[str]) -> str:
    url_decls = sorted({env_url_decl(s) for s, _, _ in all_specs})
    groups: list[str] = []
    seed_blocks: list[str] = []
    for service, spec, endpoints in all_specs:
        if service.is_auth_issuer:
            continue
        seed_js, seeds = fk_seed_setup(service, spec, endpoints, all_specs)
        if seed_js:
            seed_blocks.append(seed_js)
        groups.append(crud_flow_js(service, spec, endpoints, seeds))

    return f"""{HEADER}
{chr(10).join(url_decls)}

{PROFILES_JS}
{auth_setup_js(auth_service, token_path)}
export function setup() {{
  const token = obtainToken();
  const data = {{ token }};
{chr(10).join(seed_blocks)}
  return data;
}}

export default function (data) {{
  const params = {{
    headers: {{
      'Content-Type': 'application/json',
      Authorization: `Bearer ${{data.token}}`,
    }},
  }};

{chr(10).join(groups)}
}}
"""


def main() -> None:
    all_specs = load_all()
    auth_entry = next(((s, sp, eps) for s, sp, eps in all_specs if s.is_auth_issuer), None)
    if auth_entry is None:
        raise SystemExit("no auth-issuer service registered in openapi_common.SERVICES")
    auth_service, auth_spec, auth_endpoints = auth_entry
    token_path = discover_auth_flow(auth_spec, auth_endpoints).token_json_path

    K6_DIR.mkdir(parents=True, exist_ok=True)

    for service, spec, endpoints in all_specs:
        fname = f"{service.name.replace('Service', '').lower()}-service.js"
        if service.is_auth_issuer:
            script = generate_auth_script(service, spec, endpoints, token_path)
        else:
            script = generate_service_script(
                service, spec, endpoints, all_specs, auth_service, token_path)
        (K6_DIR / fname).write_text(script, encoding="utf-8")
        print(f"[k6] wrote {(K6_DIR / fname).relative_to(REPO_ROOT)}")

    combined = generate_combined_script(all_specs, auth_service, token_path)
    (K6_DIR / "all-services.js").write_text(combined, encoding="utf-8")
    print(f"[k6] wrote {(K6_DIR / 'all-services.js').relative_to(REPO_ROOT)}")


if __name__ == "__main__":
    main()
